### ISSUE TITLE
Elasticsearch considering removal of pluggable shards allocation in 8.0

### ISSUE THREAD

**Issue by DaveCTurner** [simplymeasured/tempest#34]
This plugin is the only implementation I can find that uses the `ClusterPlugin` interface. We are gathering feedback on removing this interface in 8.0 to allow us to make some larger changes to how shards allocation works: https://github.com/elastic/elasticsearch/issues/39464. I thought it would be a good idea to raise your awareness of this issue here.

**Comment by luflow** [comment]
Btw: this Issue was closed by the elasticsearch core team because too many companies are using that feature at the moment ;)

**Comment by DaveCTurner** [comment]
Indeed we did, sorry I forgot to close this issue too.
